### ISSUE TITLE
Crashes after "Occupying memory..."

### ISSUE THREAD

**Issue by ghost** [josemicoronil/MemoryCleaner#1]
![dfffffffffff](https://user-images.githubusercontent.com/96708048/154881599-4cdd85e0-ac2d-4d63-a048-ff3d43fbfc99.png)
Window crashes about 1 second after this, memory is still at 94% usage.

**Comment by josemirm** [comment]
Hello!
This program forces Windows to free parts of memory that aren't currently in use. If the amount of free memory doesn't change after running this program, that means that all that memory is in use and Windows cannot free any amount of memory.

Freezing about a second before is a normal behaviour in this program, and is used to ensure its correct operation. This can be watched in the "Memory" tab in the Windows Resource Monitor.

Thanks for sending the issue and I hope this is helpful to you!

**Comment by JoeMamaAME** [comment]
> Hello! This program forces Windows to free parts of memory that aren't currently in use. If the amount of free memory doesn't change after running this program, that means that all that memory is in use and Windows cannot free any amount of memory.
> 
> Freezing about a second before is a normal behaviour in this program, and is used to ensure its correct operation. This can be watched in the "Memory" tab in the Windows Resource Monitor.
> 
> Thanks for sending the issue and I hope this is helpful to you!

**Comment by ghost** [comment]
The CMD window simply closes after that Occupying memory... message. I would expect some sort of "Complete!" result at the end, instead of just exitting
